print("hello my name is tushar chauhan")
print("i am 18 years old")
print("i passed my 12th class this year only with a percantage of 78% in non medical stream")
print("i recently got admission in b.sc(cse) in pgdav college of delhi university")
print("i want to become a professional footballer as first choice in my life")
print("if i lacks opportunities in my first choice profession ")
print("then i would probably use my knowledge in programming to become a software developer")
print("and the rest depends on the god ")
print("they probably do best for their every worshipper")
print("that's all for my introduction")
print("thanks")
